### ISSUE TITLE
Dead link in blog post "The Web APIs powering the Drupal CMS trial experience"

### ISSUE THREAD

**Issue by gitressa** [mglaman/wasm-drupal#116]
I am sorry Drupal CMS trial is no longer using your WebAssembly solution ... But I am glad to hear that you'll continue updating your Drupal + WebAssembly experiment here :)

By the way, there is a dot too much in the link in the blog post, like this: [https://github.com/mglaman/wasm-drupal.](https://github.com/mglaman/wasm-drupal.)

**Comment by gitressa** [comment]
It got fixed, I think  ...

**Comment by mglaman** [comment]
It did :)
