### ISSUE TITLE
Firefox does not support ECMAScript modules in service workers

### ISSUE THREAD

**Issue by nlighteneddesign** [mglaman/wasm-drupal#21]
When I visit https://wasm-drupal.mglaman.dev/ I only get a loading ... button then I receive this error in the console:

```
Waiting for service worker... [wasm-drupal.mglaman.dev:32:21](https://wasm-drupal.mglaman.dev/)
Uncaught (in promise) TypeError: ServiceWorker script at https://wasm-drupal.mglaman.dev/worker.mjs for scope https://wasm-drupal.mglaman.dev/ threw an exception during script evaluation.
```

**Comment by nlighteneddesign** [comment]
Firefox does not support modules in service workers: https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorker#browser_compatibility

**Comment by mglaman** [comment]
Ugh Firefox supports them in [Worklet API](https://caniuse.com/mdn-api_worklet_ecmascript_modules) but not [Service Worker API](https://caniuse.com/mdn-api_serviceworker_ecmascript_modules)

**Comment by mglaman** [comment]
I can't even find the proper Firefox bug. They consider it feature complete, it seems, although it's only for Workers https://bugzilla.mozilla.org/show_bug.cgi?id=1247687

**Comment by mglaman** [comment]
Found it! https://bugzilla.mozilla.org/show_bug.cgi?id=1360870

**Comment by gitressa** [comment]
This is an amazing concept, thanks for building it @mglaman. Perhaps a note could be added on the project page, that it doesn't yet work in Firefox?

**Comment by mglaman** [comment]
Yes, I've wanted to push an update on the landing page about Firefox and Safari. I have just been really busy this morning and hopefully I will soon

**Comment by gitressa** [comment]
I feel kinda bad, and almost didn't send the comment, since I didn't want to be a negative downer ... but it sounds great with the update, thanks!

For a Firefox solution, would it help if the Drupal community got involved in the Bugzilla bug [Implement "module" service workers](https://bugzilla.mozilla.org/show_bug.cgi?id=1360870) and fixing that, or do you think it can be worked around in this project?

**Comment by mglaman** [comment]
No problem I don't see it as being a negative downer at all.

It can be worked around in this project. I need to use Rollup (or Vite to simplify Rollip config) or Webpack to bundle the assets.

**Comment by gitressa** [comment]
Sounds fantastic, I am very much looking forward to trying it.

**Comment by mglaman** [comment]
It's not a full fix, but with https://github.com/mglaman/wasm-drupal/pull/29 the two known browser issues have been linked. And if there is an error loading the service worker (FF) it shows an alert.

**Comment by mglaman** [comment]
I tried with Vite and failed miserably. I'm going to try again later with webpack just for the service worker.

**Comment by nlighteneddesign** [comment]
I just learned about https://www.rspack.dev/ which is supposed to be
webpack like and way faster

**Comment by nlighteneddesign** [comment]
Let me take a quick look at this.

**Comment by mglaman** [comment]
It looks like https://github.com/mglaman/wasm-drupal/pull/31 will fix loading. But then there are a handful of other issues, like some files being missing/corrupted. Tracking with https://github.com/mglaman/wasm-drupal/issues/32

**Comment by gitressa** [comment]
Yes, it works and I can install in Firefox, awesome!

And also as mentioned, some files are missing, but there's an issue for that, so that's already on the radar.
