### ISSUE TITLE
Replace remote Google fonts in installer with embedded fonts

### ISSUE THREAD

**Issue by gitressa** [mglaman/wasm-drupal#33]
During install, I see in [uBlock Origin](https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/) that the domain gstatic.com is contacted for Google fonts. Perhaps third-party font Noto Sans can be embedded instead, to respect user privacy?

**Comment by mglaman** [comment]
Noto is the official Drupal branding font. We can bundle it locally rather than using a third party site.

**Comment by gitressa** [comment]
I did check drupal.org, and didn't see Noto, but you probably have a point, that external sites may need to use an official branding font.

Bundling the Noto Sans font would work fine, though I am not sure how to via Github (I only ever use the GUI on Github ...) but this web site is great for downloading, and getting the paths generated:

https://gwfh.mranftl.com/fonts/noto-sans

It looks like only these two numerical weights are used in the `wasm-drupal.mglaman.dev/styles.css` file, where `bolder`, as I understand it, is a relative value:

- `font-weight:500`
- `font-weight:600`
- `font-weight:bolder`

**Comment by mglaman** [comment]
I was looking up the new branding announced at DrupalCon Portland: https://drupal.widencollective.com/portals/gfvztttq/BrandPortal

Thanks for identifying the specific weights, I'll add the files locally to the app

**Comment by gitressa** [comment]
You're welcome, and thanks for the link to the Brand Portal, I see they even have a Noto Sans font pack. Very nice. 

Including these fonts should do it, I would think. I'll try to verify it, when a new version is ready for testing, regarding fonts.

- regular
- italic
- 500
- 500 italic
- 600
- 600 italic

**Comment by mglaman** [comment]
Once https://github.com/mglaman/wasm-drupal/actions/runs/9810831878 is done, it should be fixed

**Comment by gitressa** [comment]
Perfect, I am getting Noto Sans, directly from the page, thanks!
