### ISSUE TITLE
Any issues with M1 Macs?

### ISSUE THREAD

**Issue by cosmicdreams** [mglaman/wasm-drupal#5]
Hi @mglaman I was able to run you build script and I ...think... everything worked alright.

I did get the following warning when it completed though and wanted to report it to ya
```+ docker run --name wasm-drupal-tmp --rm -v /Users/chrisweber/OpenSource/wasm-drupal/build/../drupal:/output wasm-drupal sh -c cp -r '/root/output/*' /output/
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
cp: missing file operand
Try 'cp --help' for more information.
chrisweber@MacBook-Pro build % 
```

Is there cause for concern that this build may be processor architecture specific?

**Comment by mglaman** [comment]
I didn't try it on arm64, but I know the WordPress code has a warning for it. But in their php-wasm package, not this one! Which I thought was odd. I didn't investigate beyond my tinkering today. But their repo will have clues
