### ISSUE TITLE
Install Drupal with the browser's timezone as the default for the site

### ISSUE THREAD

**Issue by mandclu-acquia** [mglaman/wasm-drupal#75]
Starshot is intended to include robust date handling capabilities, but some of them will require a properly set timezone to work as expected. Currently, when Drupal or Starshot are installed using the WASM tool, the resulting site has UTC set as its timezone.

Ideally, it would instead use the timezone that is set in the browser.

**Comment by mglaman** [comment]
Looks like we can use this https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/resolvedOptions

```
const timezone = Intl.DateTimeFormat().resolvedOptions().timeZone;
```

**Comment by mglaman** [comment]
https://git.drupalcode.org/project/drupal/-/blob/11.x/core/lib/Drupal/Core/Installer/Form/SiteConfigureForm.php?ref_type=heads#L243

Drupal sets the date via the site configure form submit, not installation parameters.

php-wasm can set it's ini settings, that should have the timezone

**Comment by mglaman** [comment]
They just started on the documentation to show how to do this: https://github.com/seanmorris/php-wasm#%EF%B8%8F-configuration
